### PR TITLE
fix control transfer

### PR DESCRIPTION
**Pull request by letoh**
Current release doesn't do control transfer correctly, that breaks all the control transfer APIs and the related functions such as `get_string_descriptor`. To do control transfer in libusb, the transfer buffer (i.e. the buffer allocated in the `ml_usb_transfer`) should be setup properly before submit.

This patch fix this issue and improve the data buffer handling in the callback. I try to send the standard requests, class requests and even vendor-specific requests in my test cases, and these APIs should work as expected.

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for your patch. Unfortunately I haven't touched ocaml-usb for a long time and I have no longer the time to maintain it. Would you be willing to take over the project?

**Comment by letoh** [comment]
Thanks for your reply. I will be happy to do that. I am still new to OCaml and don't know much about its culture. Anything I can do now?

**Comment by ghost** [comment]
Basically you can clone the project on your github and I'll put a message in the README saying that the project has moved to your github. Or maybe we can transfer ownership of the repository, I'm not sure if we can do that between user account on github but it might be possible.

Then, the next time you want to do a release, you submit a new version to the [opam repository](https://github.com/ocaml/opam-repository) with you listed as maintainer in the opam file for ocaml-usb. Then you can announce the release on the caml-list and/or discuss.ocaml.org.

I can give you more pointers for the parts you might not know, such as opam, if you want.

**Comment by letoh** [comment]
I already forked this project into my account, so I guess that transferring ownership would be failed. Maybe I need to delete my forked repo first, or just using my repo for further development and release? I have no idea which way is better.

As for opam, I do need to learn more about opam. The first thing I need to learn is publishing a new release to opam. I just read some text about `opam-publish` in the document, maybe I can simply use this tool to do that.

**Comment by ghost** [comment]
> I already forked this project into my account, so I guess that transferring ownership would be failed. Maybe I need to delete my forked repo first, or just using my repo for further development and release? I have no idea which way is better.

I suppose transferring a repository is better in general as it should keep the issues and PRs.

> As for opam, I do need to learn more about opam. The first thing I need to learn is publishing a new release to opam. I just read some text about opam-publish in the document, maybe I can simply use this tool to do that.

opam-publish works well indeed. These days the tendency is to use [jbuilder](https://github.com/janestreet/jbuilder) as build system and [topkg](https://github.com/dbuenzli/topkg) for releases. If you are interested in using these tools, I can give you some pointers.

**Comment by letoh** [comment]
I agree that transferring a repo is better. I just renamed my fork to avoid name conflict. We can try to transfer the repo now.

There are too many build systems in the OCaml world that I don't really know the difference/relationship between them. I know the jbuilder is new and might be better, but OASIS still work well for now. I would like to focus on improving the API design first and see if jbuilder or topkg is good to migrate to.

**Comment by ghost** [comment]
I just came back from holidays. I tried transferring the repository but I got this error: `letoh already has a repository in the diml/ocaml-usb network`. I think you have to delete your fork first.

**Comment by letoh** [comment]
I just deleted my fork. Please try it again.

**Comment by ghost** [comment]
done

**Comment by letoh** [comment]
Thank you, @diml .

**Pull request merged**
